/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedReviewedRouteImport } from './routes/_authenticated/reviewed'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRecordsIndexRouteImport } from './routes/_authenticated/records.index'
import { Route as AuthenticatedSupervisorRecordsIndexRouteImport } from './routes/_authenticated/supervisor.records.index'
import { Route as AuthenticatedManagerRecordsIndexRouteImport } from './routes/_authenticated/manager.records.index'
import { Route as AuthenticatedRecordsNewTypeRouteImport } from './routes/_authenticated/records.new.$type'
import { Route as AuthenticatedRecordsIdEditRouteImport } from './routes/_authenticated/records.$id.edit'
import { Route as AuthenticatedSupervisorRecordsTypeIdRouteImport } from './routes/_authenticated/supervisor.records.$type.$id'
import { Route as AuthenticatedManagerRecordsTypeIdRouteImport } from './routes/_authenticated/manager.records.$type.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewedRoute = AuthenticatedReviewedRouteImport.update({
  id: '/reviewed',
  path: '/reviewed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecordsIndexRoute =
  AuthenticatedRecordsIndexRouteImport.update({
    id: '/records/',
    path: '/records/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupervisorRecordsIndexRoute =
  AuthenticatedSupervisorRecordsIndexRouteImport.update({
    id: '/supervisor/records/',
    path: '/supervisor/records/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerRecordsIndexRoute =
  AuthenticatedManagerRecordsIndexRouteImport.update({
    id: '/manager/records/',
    path: '/manager/records/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecordsNewTypeRoute =
  AuthenticatedRecordsNewTypeRouteImport.update({
    id: '/records/new/$type',
    path: '/records/new/$type',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecordsIdEditRoute =
  AuthenticatedRecordsIdEditRouteImport.update({
    id: '/records/$id/edit',
    path: '/records/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupervisorRecordsTypeIdRoute =
  AuthenticatedSupervisorRecordsTypeIdRouteImport.update({
    id: '/supervisor/records/$type/$id',
    path: '/supervisor/records/$type/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerRecordsTypeIdRoute =
  AuthenticatedManagerRecordsTypeIdRouteImport.update({
    id: '/manager/records/$type/$id',
    path: '/manager/records/$type/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reviewed': typeof AuthenticatedReviewedRoute
  '/users': typeof AuthenticatedUsersRoute
  '/records/': typeof AuthenticatedRecordsIndexRoute
  '/records/$id/edit': typeof AuthenticatedRecordsIdEditRoute
  '/records/new/$type': typeof AuthenticatedRecordsNewTypeRoute
  '/manager/records/': typeof AuthenticatedManagerRecordsIndexRoute
  '/supervisor/records/': typeof AuthenticatedSupervisorRecordsIndexRoute
  '/manager/records/$type/$id': typeof AuthenticatedManagerRecordsTypeIdRoute
  '/supervisor/records/$type/$id': typeof AuthenticatedSupervisorRecordsTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reviewed': typeof AuthenticatedReviewedRoute
  '/users': typeof AuthenticatedUsersRoute
  '/records': typeof AuthenticatedRecordsIndexRoute
  '/records/$id/edit': typeof AuthenticatedRecordsIdEditRoute
  '/records/new/$type': typeof AuthenticatedRecordsNewTypeRoute
  '/manager/records': typeof AuthenticatedManagerRecordsIndexRoute
  '/supervisor/records': typeof AuthenticatedSupervisorRecordsIndexRoute
  '/manager/records/$type/$id': typeof AuthenticatedManagerRecordsTypeIdRoute
  '/supervisor/records/$type/$id': typeof AuthenticatedSupervisorRecordsTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/reviewed': typeof AuthenticatedReviewedRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/records/': typeof AuthenticatedRecordsIndexRoute
  '/_authenticated/records/$id/edit': typeof AuthenticatedRecordsIdEditRoute
  '/_authenticated/records/new/$type': typeof AuthenticatedRecordsNewTypeRoute
  '/_authenticated/manager/records/': typeof AuthenticatedManagerRecordsIndexRoute
  '/_authenticated/supervisor/records/': typeof AuthenticatedSupervisorRecordsIndexRoute
  '/_authenticated/manager/records/$type/$id': typeof AuthenticatedManagerRecordsTypeIdRoute
  '/_authenticated/supervisor/records/$type/$id': typeof AuthenticatedSupervisorRecordsTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/dashboard'
    | '/pending'
    | '/reports'
    | '/reviewed'
    | '/users'
    | '/records/'
    | '/records/$id/edit'
    | '/records/new/$type'
    | '/manager/records/'
    | '/supervisor/records/'
    | '/manager/records/$type/$id'
    | '/supervisor/records/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/dashboard'
    | '/pending'
    | '/reports'
    | '/reviewed'
    | '/users'
    | '/records'
    | '/records/$id/edit'
    | '/records/new/$type'
    | '/manager/records'
    | '/supervisor/records'
    | '/manager/records/$type/$id'
    | '/supervisor/records/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/dashboard'
    | '/_authenticated/pending'
    | '/_authenticated/reports'
    | '/_authenticated/reviewed'
    | '/_authenticated/users'
    | '/_authenticated/records/'
    | '/_authenticated/records/$id/edit'
    | '/_authenticated/records/new/$type'
    | '/_authenticated/manager/records/'
    | '/_authenticated/supervisor/records/'
    | '/_authenticated/manager/records/$type/$id'
    | '/_authenticated/supervisor/records/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviewed': {
      id: '/_authenticated/reviewed'
      path: '/reviewed'
      fullPath: '/reviewed'
      preLoaderRoute: typeof AuthenticatedReviewedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/records/': {
      id: '/_authenticated/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof AuthenticatedRecordsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supervisor/records/': {
      id: '/_authenticated/supervisor/records/'
      path: '/supervisor/records'
      fullPath: '/supervisor/records/'
      preLoaderRoute: typeof AuthenticatedSupervisorRecordsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/records/': {
      id: '/_authenticated/manager/records/'
      path: '/manager/records'
      fullPath: '/manager/records/'
      preLoaderRoute: typeof AuthenticatedManagerRecordsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/records/new/$type': {
      id: '/_authenticated/records/new/$type'
      path: '/records/new/$type'
      fullPath: '/records/new/$type'
      preLoaderRoute: typeof AuthenticatedRecordsNewTypeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/records/$id/edit': {
      id: '/_authenticated/records/$id/edit'
      path: '/records/$id/edit'
      fullPath: '/records/$id/edit'
      preLoaderRoute: typeof AuthenticatedRecordsIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supervisor/records/$type/$id': {
      id: '/_authenticated/supervisor/records/$type/$id'
      path: '/supervisor/records/$type/$id'
      fullPath: '/supervisor/records/$type/$id'
      preLoaderRoute: typeof AuthenticatedSupervisorRecordsTypeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/records/$type/$id': {
      id: '/_authenticated/manager/records/$type/$id'
      path: '/manager/records/$type/$id'
      fullPath: '/manager/records/$type/$id'
      preLoaderRoute: typeof AuthenticatedManagerRecordsTypeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReviewedRoute: typeof AuthenticatedReviewedRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedRecordsIndexRoute: typeof AuthenticatedRecordsIndexRoute
  AuthenticatedRecordsIdEditRoute: typeof AuthenticatedRecordsIdEditRoute
  AuthenticatedRecordsNewTypeRoute: typeof AuthenticatedRecordsNewTypeRoute
  AuthenticatedManagerRecordsIndexRoute: typeof AuthenticatedManagerRecordsIndexRoute
  AuthenticatedSupervisorRecordsIndexRoute: typeof AuthenticatedSupervisorRecordsIndexRoute
  AuthenticatedManagerRecordsTypeIdRoute: typeof AuthenticatedManagerRecordsTypeIdRoute
  AuthenticatedSupervisorRecordsTypeIdRoute: typeof AuthenticatedSupervisorRecordsTypeIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReviewedRoute: AuthenticatedReviewedRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedRecordsIndexRoute: AuthenticatedRecordsIndexRoute,
  AuthenticatedRecordsIdEditRoute: AuthenticatedRecordsIdEditRoute,
  AuthenticatedRecordsNewTypeRoute: AuthenticatedRecordsNewTypeRoute,
  AuthenticatedManagerRecordsIndexRoute: AuthenticatedManagerRecordsIndexRoute,
  AuthenticatedSupervisorRecordsIndexRoute:
    AuthenticatedSupervisorRecordsIndexRoute,
  AuthenticatedManagerRecordsTypeIdRoute:
    AuthenticatedManagerRecordsTypeIdRoute,
  AuthenticatedSupervisorRecordsTypeIdRoute:
    AuthenticatedSupervisorRecordsTypeIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
